### ISSUE TITLE
Checkov is hanging on execution

### ISSUE THREAD

**Issue by anhdle14** [antonbabenko/pre-commit-terraform#164]
The `checkov` task hang with newer checkov version. (currently 1.0.679)

---
## pre-commit-config.yaml

```yaml
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
    - id: terraform_docs
    - id: terraform_tfsec
    - id: checkov
```

---
## Problems detail

```bash
$ pre-commit run -a
# This will hang...
Checkov..................................................................

$ cat ~/.cache/pre-commit/pre-commit.log
### version information
pre-commit version: 2.7.1
sys.version:
    3.8.6 (default, Dec  8 2020, 20:58:28) 
    [Clang 7.1.0 (tags/RELEASE_710/final)]
sys.executable: /nix/store/c56kq0k3f3rdgkj3s1z5hw0j4ack9gdg-python3-3.8.6/bin/python3.8
os.name: posix
sys.platform: darwin

### error information

Interrupted (^C): KeyboardInterrupt: 


Traceback (most recent call last):
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/error_handler.py", line 63, in error_handler
    yield
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/main.py", line 390, in main
    return run(args.config, store, args)
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/commands/run.py", line 390, in run
    return _run_hooks(config, hooks, args, environ)
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/commands/run.py", line 272, in _run_hooks
    current_retval, prior_diff = _run_single_hook(
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/commands/run.py", line 182, in _run_single_hook
    retcode, out = language.run_hook(hook, filenames, use_color)
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/languages/python.py", line 224, in run_hook
    return helpers.run_xargs(hook, hook.cmd, file_args, color=color)
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/languages/helpers.py", line 109, in run_xargs
    return xargs(cmd, file_args, **kwargs)
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/xargs.py", line 153, in xargs
    for proc_retcode, proc_out, _ in results:
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/xargs.py", line 145, in run_cmd_partition
    return cmd_fn(
  File "/nix/store/9jghh7l474yalz1nlpx3yswp3zvkp7h4-python3.8-pre-commit-2.7.1/lib/python3.8/site-packages/pre_commit/util.py", line 235, in cmd_output_p
    bts = os.read(pty.r, 4096)
KeyboardInterrupt
$ checkov -d '.'
# This run like normal
```

Not sure what could cause this but I am down to do more testing if needed.

**Comment by MaxymVlasov** [comment]
I just check with the latest versions of `checkov` and `pre-commit-terraform` and all works fine

```yaml
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.50.0
  hooks:
    # - id: terraform_fmt
    # - id: terraform_tflint
    # - id: terraform_docs
    # - id: terraform_tfsec
    - id: checkov
```

```bash
$ checkov -v    
2.0.395
```
