### ISSUE TITLE
[checkov] Terraform_checkov stage failing on authentication

### ISSUE THREAD

**Issue by NiallJude** [antonbabenko/pre-commit-terraform#529]
The `terraform_checkov` stage is failing on multiple repositories locally.
The error is complaining about an authentication token being expired or missing.
However, I am unaware of ever having set a token, set up an account over on Bridgecrew and it used to run fine as part of pre-commit.

```
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.80.0
  hooks:
    # TF Fmt
    - id: terraform_fmt
      args:
      - --args=-check
      - --args=-diff
      - --args=-write=true
    
    # TF Validate
    - id: terraform_validate
      args:
      - --args=-json
      - --args=-no-color 
    
    # Checkov
    - id: terraform_checkov
      args:
      - --args=--quiet
    
    # Terraform Docs
    - id: terraform_docs
      args:
      - --hook-config=--add-to-existing-file=true     
      - --hook-config=--create-file-if-not-exist=true
    
    # TF Lint
    - id: terraform_tflint
      args:
      # Manually Enabled Rules
      - --args=--enable-rule=terraform_typed_variables
      # Manually Disabled Rules
      - --args=--disable-rule=terraform_documented_variables
      - --args=--disable-rule=terraform_module_version
      - --args=--disable-rule=terraform_required_providers
      - --args=--disable-rule=terraform_required_version
      - --args=--disable-rule=terraform_unused_declarations
```

The error is as below:

```
Checkov..................................................................Failed
- hook id: terraform_checkov
- exit code: 2

2023-05-31 12:01:28,864 [MainThread  ] [ERROR]  Received an error response during authentication
2023-05-31 12:01:28,869 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/main.py", line 355, in run
    bc_integration.setup_bridgecrew_credentials(repo_id=self.config.repo_id,
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 263, in setup_bridgecrew_credentials
    self.set_s3_integration()
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 276, in set_s3_integration
    repo_full_path, support_path, response = self.get_s3_role(self.repo_id)  # type: ignore
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 327, in get_s3_role
    response = self._get_s3_creds(repo_id, token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/common/bridgecrew/platform_integration.py", line 354, in _get_s3_creds
    raise BridgecrewAuthError(error_message)
checkov.common.bridgecrew.platform_errors.BridgecrewAuthError: BCAuthError, Received unexpected response from platform (status code 403). Please verify that your API token is valid and has permissions to call the Bridgecrew APIs.The key must be associated with any role besides Auditor. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/main.py", line 385, in run
    self.exit_run()
  File "/opt/homebrew/Cellar/checkov/2.3.240/libexec/lib/python3.11/site-packages/checkov/main.py", line 589, in exit_run
    exit(0) if self.config.no_fail_on_crash else exit(2)
                                                 ^^^^^^^
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 2`
```

Are there some new steps involved in authentication for Checkov? It is possible this issue is not related to pre-commit-terraform. However, I wanted to flag it in case it is a known issue.

**Comment by MaxymVlasov** [comment]
@NiallJude hi
These errors go from `checkov` itself.

>(status code 403). Please verify that your API token is valid and has permission to call the Bridgecrew APIs.The key must be associated with any role besides Auditor.

Could you try to fix that error as specified in error msg?

If no luck - run `checkov` without `pre-commit-terraform`, and in case `checkov` produce an error - create an issue for https://github.com/bridgecrewio/checkov

 In case `checkov` works but `pre-commit-terraform` hook - not please let us know
