### ISSUE TITLE
checkov unable to find its baseline file

### ISSUE THREAD

**Issue by lpossamai** [antonbabenko/pre-commit-terraform#533]
### Describe the bug

I can successfully run `checkov -d terraform/ --baseline .checkov.baseline` or `pre-commit run terraform_checkov -a`. However, when I try to commit some files, where `pre-commit` will run automatically because of `pre-commit install`, I get the following error:

```
Checkov..................................................................Failed
- hook id: terraform_checkov
- exit code: 1

grep: warning: stray \ before /
2023-06-16 11:44:39,440 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "/home/lucas/.local/lib/python3.11/site-packages/checkov/main.py", line 451, in run
    baseline.from_json(self.config.baseline)
  File "/home/lucas/.local/lib/python3.11/site-packages/checkov/common/output/baseline.py", line 96, in from_json
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.checkov.baseline'
Traceback (most recent call last):
  File "/home/lucas/.local/bin/checkov", line 9, in <module>
    sys.exit(Checkov().run())
             ^^^^^^^^^^^^^^^
  File "/home/lucas/.local/lib/python3.11/site-packages/checkov/main.py", line 451, in run
    baseline.from_json(self.config.baseline)
  File "/home/lucas/.local/lib/python3.11/site-packages/checkov/common/output/baseline.py", line 96, in from_json
    with open(file_path, "r") as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.checkov.baseline'
``` 

My `.pre-commit-config.yaml` file looks like this:
```
- id: terraform_checkov
            args:
              - --args=--quiet
              - --args=--framework=terraform
              - --args=--download-external-modules false
              - --args=--baseline=.checkov.baseline
```

### Environment information

* OS: Fedora 38
```
Linux jarvis.localdomain 6.3.7-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun  9 15:21:11 UTC 2023 x86_64 GNU/Linux
```

**Comment by yermulnik** [comment]
@lpossamai Seems like what Anton pointed here https://github.com/antonbabenko/pre-commit-terraform/issues/530#issuecomment-1577263236 is what you're looking for. Please try that out and confirm.

**Comment by MaxymVlasov** [comment]
Yeah, @yermulnik is right.

Check second point in [hook related docs](https://github.com/antonbabenko/pre-commit-terraform#checkov-deprecated-and-terraform_checkov)

![image](https://github.com/antonbabenko/pre-commit-terraform/assets/11096782/d33d26d6-9ffe-4e5b-a6ea-37fcf5fedb3b)
